### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by johndpope** [arondn2/loopback-visible-properties-mixin#1]
Do you have any suggestion for some models
Eg. 
Account 
When I go to api as logged in user / I want to know all fields

But say if I surface this account model

For get friends 

I want to have fields hidden

Should I use a subclass or ???

Create a pseudo model 
PrivateAccount

**Comment by alexkander** [comment]
I think one way to do this is to create a model with a different access rights setting for each case, and if you need it, both models could have the same table in the data source.
```
// base-account.json
{
  "name": "BaseAccount",
  "base": "PersistedModel",
  "options": {
    "mysql": {
      "table": "account"
    }
  },
  "properties": {
    "name": "string",
    "email": "string"
  }
}

// private-account.json
{
  "name": "PrivateAccount",
  "base": "BaseAccount",
  "mixins": {
    "VisibleProperties": {
      "fields": [
        "id",
        "name",
        "email"
      ]
    }
  }
}

// public-account.json
{
  "name": "PublicAccount",
  "base": "BaseAccount",
  "mixins": {
    "VisibleProperties": {
      "fields": [
        "name"
      ]
    }
  }
}
```

**Comment by johndpope** [comment]
thx
